# Updated by bot: Add Git SHA to Docker image tags for better versioning: tags: ashwanth01/ashapp-backend:latest,ashwanth01/ashapp-backend:${{ github.sha }}
# Updated by bot: Use Git SHA for versioning: tags: ashwanth01/ashapp-backend:latest,ashwanth01/ashapp-backend:${{ github.sha }}
# Updated by bot: Use Git SHA or another versioning scheme for Docker image tags, e.g., tags: ashwanth01/ashapp-backend:latest,ashwanth01/ashapp-backend:${{ github.sha }}
# Updated by bot: Use Git SHA or another versioning scheme for Docker image tags, e.g., tags: ashwanth01/ashapp-backend:latest,ashwanth01/ashapp-backend:${{ github.sha }}
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ashwanth01
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ashwanth01/ashapp-backend:latest

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Get Service NodePort URL
      run: |
        NODE_IP=$(hostname -I | awk '{print $1}')
        echo "App running at: http://$NODE_IP:30080"

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/ashapp-backend
        kubectl get pods -l app=ashapp-backend

    - name: Test application
      run: |
        sleep 30
        curl -f http://$NODE_IP:30080 || exit 1

    - name: Cleanup
      if: failure()
      run: |
        kubectl delete deployment ashapp-backend
        kubectl delete service ashapp-backend

# Appended by bot: Use Git SHA or another versioning scheme for Docker image tags, e.g., tags: ashwanth01/ashapp-backend:latest,ashwanth01/ashapp-backend:${{ github.sha }}

# Appended by bot: Use Git SHA or another versioning scheme for Docker image tags, e.g., tags: ashwanth01/ashapp-backend:latest,ashwanth01/ashapp-backend:${{ github.sha }}

# Appended by bot: Use Git SHA or another versioning scheme for Docker image tags, e.g., tags: ashwanth01/ashapp-backend:latest,ashwanth01/ashapp-backend:${{ github.sha }}
# Appended by bot: Add Git SHA to Docker image tags for better versioning: tags: ashwanth01/ashapp-backend:latest,ashwanth01/ashapp-backend:${{ github.sha }}
